// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowManagement.Data;

#nullable disable

namespace WorkflowManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkflowManagement.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Owner")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Owner");

                    b.Property<string>("TimeCreated")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("TimeCreated");

                    b.HasKey("Id");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("WorkflowManagement.Entities.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("NoOfTickets")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NoOfTickets");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("OwnerName");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("WorkflowManagement.Entities.BugTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualResult")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("actual_result");

                    b.Property<string>("Asignee")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asignee");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("expected_result");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Reporter")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("reporter");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("status");

                    b.Property<string>("StepsToReproduce")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("steps_to_reproduce");

                    b.HasKey("Id");

                    b.ToTable("BugTicket");
                });

            modelBuilder.Entity("WorkflowManagement.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
